name: dataflower
version: 0.3.0.0
synopsis: A Pure-Haskell Timely Dataflow System
description: See README
maintainer: Jesse Kempf
github: doublecrowngaming/dataflower

ghc-options: -Wall -O2

default-extensions:
- StrictData

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - store
  - vector

library:
  source-dirs: src
  exposed-modules:
    - Dataflow
    - Dataflow.Operators
    - Test.Dataflow
  dependencies:
    - hashable
    - mtl
    - pretty-show
    - stm
    - time
    - transformers

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - dataflower
      - hspec >=2.0.0
      - QuickCheck
      - stm

benchmarks:
  performance:
    main: Main.hs
    source-dirs: benchmark
    dependencies:
      - dataflower
      - criterion
      - stm
    ghc-options: -O2
